name: Deploy Pages

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:
env:
  SECRET_QIITA: ${{secrets.QIITA_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
